version: '3.8'

services:
  frog-app:
    build:
      context: . 
      dockerfile: Dockerfile 

    image: frog-app
    volumes:
      - .:/frog-app
    container_name: frog_app
    environment:
      - DISPLAY=${DISPLAY}
    network_mode: "host"  
    privileged: true  
    restart: "no"
